// src/utils/constant.js

const constant =  {
  "home": {
    "text": "¡Feliz  Cumpleaños  Di!",
    "principal": "Te recuerdo que llevamos",
    "secondary": "días juntos",
  },
  "effectsMessage": {
    "hearts": "Nuestro amor crece por cada corazón en el aire.",
    "stars": "Un amor eterno, como las estrellas en el universo.",
    "goodNight": "De pronto es de noche, buenas noches mi amor!"
  },
  "birthdayDate": "2025-06-01",
  "daysTogether": "2023-10-21",
  "loaderText": "* MI AMOR * FELIZ CUMPLEAÑOS *",
  "heartText": "Mi corazón late por ti todos los días.",
  "titleCountdown": "* ESTE REGALO * SE DESBLOQUEA * EN ",
  "maxImgDaily": 3,
  "defaultImage": {
    "src": "/images/come-back-tomorrow.png",
    "description": "Lo siento mi amor es todo por hoy, regresa mañana por 3 fotos más.",
  },
  "polaroids": [
    {
      "src": "/images/viaje-a-chancay-1.png",
      "description": "Viaje a castillo de Chancay estilo DreamWorks.",
    },
    {
      "src": "/images/sebas-y-di-playa-3.png",
      "description": "Nosotros en la playa estilo GTA.",
    },
    {
      "src": "/images/sebas-y-di-potter-1.png",
      "description": "Juntos en el mundo de Harry Potter.",
    },
    {
      "src": "/images/cita-en-mac-1.png",
      "description": "Una cita especial.",
    },
    {
      "src": "/images/primera-navidad-2.png",
      "description": "Nuestra primera navidad.",
    },
    {
      "src": "/images/primera-cita-1.png",
      "description": "Primera Cita.",
    },
  ],
  "pageTitleMovies": "Peliculas que hemos visto juntos en el cine:",
  "movies": [
    "1. Barbie",
    "2. Escabe bajo fuego",
    "3. Gran Turismo",
    "4. Dobles de acción",
    "5. Los indestructibles 4",
    "6. Los increibles",
    "7. Toy Story",
    "8. Sin Aire",
    "9. Five Night at Freddy's",
    "10. Coco",
    "11. El Justiciero: Capítulo Final",
    "12. Los Juegos del hambre: Balada de pájaron cantores y serpientes",
    "13. Wish: El poder de los deseos",
    "14. Hipnosis: Arma invisible",
    "15. Wonka",
    "16. Venganza silenciosa",
    "17. Viernes negro",
    "18. Aquaman 2: El reino perdido",
    "19. Hojas de Otoño",
    "20. El juego de la muerte",
    "21. Muerto de risa",
    "22. Con todo menos contigo",
    "23. Beekeeper: sentencia de muerte",
    "24. Pobres criaturas",
    "25. Vidas pasadas",
    "26. Cuando asecha la maldad",
    "27. Madame web",
    "28. Demon Slayer: To the hasher training",
    "29. Red",
    "30. Ferrari",
    "31. Garra de hierro",
    "32. Sleep: El mal no duerme",
    "33. Kung fu panda 4",
    "34. Alicia en el país de las pesadillas",
    "35. Godzilla y Kong: El nuevo imperio",
    "36. Arthur",
    "37. Ghostbusters: apocalipsis fantasma",
    "38. Back to black",
    "39. Profesión peligro",
    "40. Vaguito",
    "41. Desafiantes",
    "42. Guerra civil",
    "43. Lazos de vida",
    "44. Gardfield: Fuera de casa",
    "45. Amigos imaginario",
    "46. Los extraños: Capitulo 1",
    "47. Furiosa: De la saga Mad Max",
    "48: Harry Potter y el prisionero de Azkabam",
    "49: Hachiko 2: Siempre a tu lado",
    "50: Bad boys: Hasta la muerte",
    "51: Monkey Man: El despertar de la bestia",
    "52: Intensamente 2",
    "53: Un lugar en silencio: Día uno",
    "54: Deadpool & Wolverine",
    "55: De noche con el diablo",
    "56: Tornados",
    "57: Cómplices del engaño",
    "58: Romper el circulo",
    "59: La trampa",
    "60: Harry Potter y la piedra filosofal",
    "61: Longlegs: Coleccionista de almas",
    "62: Sherk 2",
    "63: Coraline",
    "64: Parpadea 2 veces",
    "65: Exhuma: La tumba del diablo",
    "66: No hables con extraños",
    "67: La sustancia",
    "68: Sonrie 2",
    "69: Venom: El ultimo baile",
    "70: El tiempo que tenemos",
    "71: Gladiador II",
    "71: Wicked",
    "73: Kraven el cazador",
    "74: Mufasa el rey león",
    "75: Interestelar",
    "76: El robo perfecto: Pantera",
    "77: Compañera perfecta",
    "78: Cónclave",
    "79: Blanca Nieves",
    "80: Rescate implacable",
    "81: El amateur: Operación Venganza",
    "82: Pecadores",
    "83: Thunderbolts",
    "84: Karate Kid Leyendas",
    "85: Destino final: Lazos de Sangre",
    "86: Mission Impossible Sentencia final",
    "87: Encerrado",
    "88: Bailarina",
    "89: Como entrenar a tu dragon",
  ]
}

export default constant;
