// src/utils/constant.js

const constant =  {
  "home": {
    "text": "¡Feliz  Cumpleaños  Di!",
    "principal": "Te recuerdo que llevamos",
    "secondary": "días juntos",
  },
  "effectsMessage": {
    "hearts": "Nuestro amor crece por cada corazón en el aire.",
    "stars": "Un amor eterno, como las estrellas en el universo.",
    "goodNight": "De pronto es de noche, buenas noches mi amor!"
  },
  "birthdayDate": "2025-06-01",
  "daysTogether": "2023-10-21",
  "loaderText": "* MI AMOR * FELIZ CUMPLEAÑOS *",
  "heartText": "Mi corazón late por ti todos los días.",
  "titleCountdown": "* ESTE REGALO * SE DESBLOQUEA * EN ",
  "maxImgDaily": 3,
  "defaultImage": {
    "src": "/images/come-back-tomorrow.png",
    "description": "Lo siento mi amor es todo por hoy, regresa mañana por 3 fotos más.",
  },
  "polaroids": [
    {
      "src": "/images/viaje-a-chancay-1.png",
      "description": "Viaje a castillo de Chancay estilo DreamWorks.",
    },
    {
      "src": "/images/sebas-y-di-playa-3.png",
      "description": "Nosotros en la playa estilo GTA.",
    },
    {
      "src": "/images/sebas-y-di-potter-1.png",
      "description": "Juntos en el mundo de Harry Potter.",
    },
    {
      "src": "/images/cita-en-mac-1.png",
      "description": "Una cita especial.",
    },
    {
      "src": "/images/primera-navidad-2.png",
      "description": "Nuestra primera navidad.",
    },
    {
      "src": "/images/primera-cita-1.png",
      "description": "Primera Cita.",
    },
  ],
  "pageTitleMovies": "Peliculas que hemos visto juntos en el cine:",
  "movies": [
    { "title": "1. Barbie", "image": "/images/movies/0.webp" },
    { "title": "2. Escabe bajo fuego", "image": "/images/movies/1.webp" },
    { "title": "3. Gran Turismo", "image": "/images/movies/2.webp" },
    { "title": "4. Dobles de acción", "image": "/images/movies/3.webp" },
    { "title": "5. Los indestructibles 4", "image": "/images/movies/4.webp"},
    { "title": "6. Los increibles", "image": "/images/movies/5.webp" },
    { "title": "7. Toy Story", "image": "/images/movies/6.webp" },
    { "title": "8. Sin Aire", "image": "/images/movies/7.webp" },
    { "title": "9. Five Night at Freddy's", "image": "/images/movies/8.webp"},
    { "title": "10. Coco", "image": "/images/movies/9.webp" },
    { "title": "11. El Justiciero: Capítulo Final", "image": "/images/movies/10.webp" },
    { "title": "12. Los Juegos del hambre: Balada de pájaron cantores y serpientes", "image": "/images/movies/11.webp" },
    { "title": "13. Wish: El poder de los deseos", "image": "/images/movies/12.webp" },
    { "title": "14. Hipnosis: Arma invisible", "image": "/images/movies/13.webp" },
    { "title": "15. Wonka", "image": "/images/movies/14.webp" },
    { "title": "16. Venganza silenciosa", "image": "/images/movies/15.webp" },
    { "title": "17. Viernes negro", "image": "/images/movies/16.webp" },
    { "title": "18. Aquaman 2: El reino perdido", "image": "/images/movies/17.webp" },
    { "title": "19. Hojas de Otoño", "image": "/images/movies/18.webp" },
    { "title": "20. El juego de la muerte", "image": "/images/movies/19.webp" },
    { "title": "21. Muerto de risa", "image": "/images/movies/20.webp" },
    { "title": "22. Con todo menos contigo", "image": "/images/movies/21.webp" },
    { "title": "23. Beekeeper: sentencia de muerte", "image": "/images/movies/22.webp" },
    { "title": "24. Pobres criaturas", "image": "/images/movies/23.webp"},
    { "title": "25. Vidas pasadas", "image": "/images/movies/24.webp"},
    { "title": "26. Cuando asecha la maldad", "image": "/images/movies/25.webp"},
    { "title": "27. Madame web", "image": "/images/movies/26.webp"},
    { "title": "28. Demon Slayer: To the hasher training", "image": "/images/movies/27.webp"},
    { "title": "29. Red", "image": "/images/movies/28.webp"},
    { "title": "30. Ferrari", "image": "/images/movies/29.webp"},
    { "title": "31. Garra de hierro", "image": "/images/movies/30.webp"},
    { "title": "32. Sleep: El mal no duerme", "image": "/images/movies/31.webp"},
    { "title": "33. Kung fu panda 4", "image": "/images/movies/32.webp"},
    { "title": "34. Alicia en el país de las pesadillas", "image": "/images/movies/33.webp"},
    { "title": "35. Godzilla y Kong: El nuevo imperio", "image": "/images/movies/34.webp"},
    { "title": "36. Arthur", "image": "/images/movies/35.webp"},
    { "title": "37. Ghostbusters: apocalipsis fantasma", "image": "/images/movies/36.webp"},
    { "title": "38. Back to black", "image": "/images/movies/37.webp"},
    { "title": "39. Profesión peligro", "image": "/images/movies/38.webp"},
    { "title": "40. Vaguito", "image": "/images/movies/39.webp"},
    { "title": "41. Desafiantes", "image": "/images/movies/40.webp"},
    { "title": "42. Guerra civil", "image": "/images/movies/41.webp"},
    { "title": "43. Lazos de vida", "image": "/images/movies/42.webp"},
    { "title": "44. Gardfield: Fuera de casa", "image": "/images/movies/43.webp"},
    { "title": "45. Amigos imaginario", "image": "/images/movies/44.webp"},
    { "title": "46. Los extraños: Capitulo 1", "image": "/images/movies/45.webp"},
    { "title": "47. Furiosa: De la saga Mad Max", "image": "/images/movies/46.webp"},
    { "title": "48: Harry Potter y el prisionero de Azkabam", "image": "/images/movies/47.webp"},
    { "title": "49: Hachiko 2: Siempre a tu lado", "image": "/images/movies/48.webp"},
    { "title": "50: Bad boys: Hasta la muerte", "image": "/images/movies/49.webp"},
    { "title": "51: Monkey Man: El despertar de la bestia", "image": "/images/movies/50.webp"},
    { "title": "52: Intensamente 2", "image": "/images/movies/51.webp"},
    { "title": "53: Un lugar en silencio: Día uno", "image": "/images/movies/52.webp"},
    { "title": "54: Deadpool & Wolverine", "image": "/images/movies/53.webp"},
    { "title": "55: De noche con el diablo" , "image": "/images/movies/54.webp"},
    { "title": "56: Tornados", "image": "/images/movies/55.webp"},
    { "title": "57: Cómplices del engaño" , "image": "/images/movies/56.webp"},
    { "title": "58: Romper el circulo", "image": "/images/movies/57.webp"},
    { "title": "59: La trampa", "image": "/images/movies/58.webp"},
    { "title": "60: Harry Potter y la piedra filosofal", "image": "/images/movies/59.webp"},
    { "title": "61: Longlegs: Coleccionista de almas", "image": "/images/movies/60.webp"},
    { "title": "62: Sherk 2", "image": "/images/movies/61.webp"},
    { "title": "63: Coraline", "image": "/images/movies/62.webp"},
    { "title": "64: Parpadea 2 veces", "image": "/images/movies/63.webp"},
    { "title": "65: Exhuma: La tumba del diablo", "image": "/images/movies/64.webp"},
    { "title": "66: No hables con extraños", "image": "/images/movies/65.webp"},
    { "title": "67: La sustancia", "image": "/images/movies/66.webp"},
    { "title": "68: Sonrie 2", "image": "/images/movies/67.webp"},
    { "title": "69: Venom: El ultimo baile", "image": "/images/movies/68.webp"},
    { "title": "70: El tiempo que tenemos", "image": "/images/movies/69.webp"},
    { "title": "71: Gladiador II", "image": "/images/movies/70.webp"},
    { "title": "72: Wicked", "image": "/images/movies/71.webp"},
    { "title": "73: Kraven el cazador", "image": "/images/movies/72.webp"},
    { "title": "74: Mufasa el rey león", "image": "/images/movies/73.webp"},
    { "title": "75: Interestelar", "image": "/images/movies/74.webp"},
    { "title": "76: El robo perfecto: Pantera", "image": "/images/movies/75.webp"},
    { "title": "77: Compañera perfecta", "image": "/images/movies/76.webp"},
    { "title": "78: Cónclave", "image": "/images/movies/77.webp"},
    { "title": "79: Blanca Nieves", "image": "/images/movies/78.webp"},
    { "title": "80: Rescate implacable", "image": "/images/movies/79.webp"},
    { "title": "81: El amateur: Operación Venganza", "image": "/images/movies/80.webp"},
    { "title": "82: Pecadores", "image": "/images/movies/81.webp"},
    { "title": "83: Thunderbolts", "image": "/images/movies/82.webp"},
    { "title": "84: Karate Kid Leyendas", "image": "/images/movies/83.webp"},
    { "title": "85: Destino final: Lazos de Sangre", "image": "/images/movies/84.webp"},
    { "title": "86: Mission Impossible Sentencia final", "image": "/images/movies/85.webp"},
    { "title": "87: Encerrado", "image": "/images/movies/86.webp"},
    { "title": "88: Bailarina", "image": "/images/movies/87.webp"},
  ]
}

export default constant;
